// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/cache.dart';
import 'api/eq.dart';
import 'api/wave.dart';
import 'api/yandex.dart';

import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AccountDto dco_decode_account_dto(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  EqSettingsDto dco_decode_box_autoadd_eq_settings_dto(dynamic raw);

  @protected
  EqStateDto dco_decode_box_autoadd_eq_state_dto(dynamic raw);

  @protected
  TrackDto dco_decode_box_autoadd_track_dto(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  CacheStatsDto dco_decode_cache_stats_dto(dynamic raw);

  @protected
  DeviceCodeDto dco_decode_device_code_dto(dynamic raw);

  @protected
  EqBandDto dco_decode_eq_band_dto(dynamic raw);

  @protected
  EqModeDto dco_decode_eq_mode_dto(dynamic raw);

  @protected
  EqPresetDto dco_decode_eq_preset_dto(dynamic raw);

  @protected
  EqSettingsDto dco_decode_eq_settings_dto(dynamic raw);

  @protected
  EqStateDto dco_decode_eq_state_dto(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  FilterKindDto dco_decode_filter_kind_dto(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<EqBandDto> dco_decode_list_eq_band_dto(dynamic raw);

  @protected
  List<EqPresetDto> dco_decode_list_eq_preset_dto(dynamic raw);

  @protected
  List<PlaylistDto> dco_decode_list_playlist_dto(dynamic raw);

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<TrackDto> dco_decode_list_track_dto(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  PlaySourceDto dco_decode_play_source_dto(dynamic raw);

  @protected
  PlaylistDto dco_decode_playlist_dto(dynamic raw);

  @protected
  StreamDto dco_decode_stream_dto(dynamic raw);

  @protected
  TrackDto dco_decode_track_dto(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AccountDto sse_decode_account_dto(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  EqSettingsDto sse_decode_box_autoadd_eq_settings_dto(
    SseDeserializer deserializer,
  );

  @protected
  EqStateDto sse_decode_box_autoadd_eq_state_dto(SseDeserializer deserializer);

  @protected
  TrackDto sse_decode_box_autoadd_track_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  CacheStatsDto sse_decode_cache_stats_dto(SseDeserializer deserializer);

  @protected
  DeviceCodeDto sse_decode_device_code_dto(SseDeserializer deserializer);

  @protected
  EqBandDto sse_decode_eq_band_dto(SseDeserializer deserializer);

  @protected
  EqModeDto sse_decode_eq_mode_dto(SseDeserializer deserializer);

  @protected
  EqPresetDto sse_decode_eq_preset_dto(SseDeserializer deserializer);

  @protected
  EqSettingsDto sse_decode_eq_settings_dto(SseDeserializer deserializer);

  @protected
  EqStateDto sse_decode_eq_state_dto(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  FilterKindDto sse_decode_filter_kind_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<EqBandDto> sse_decode_list_eq_band_dto(SseDeserializer deserializer);

  @protected
  List<EqPresetDto> sse_decode_list_eq_preset_dto(SseDeserializer deserializer);

  @protected
  List<PlaylistDto> sse_decode_list_playlist_dto(SseDeserializer deserializer);

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<TrackDto> sse_decode_list_track_dto(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  PlaySourceDto sse_decode_play_source_dto(SseDeserializer deserializer);

  @protected
  PlaylistDto sse_decode_playlist_dto(SseDeserializer deserializer);

  @protected
  StreamDto sse_decode_stream_dto(SseDeserializer deserializer);

  @protected
  TrackDto sse_decode_track_dto(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_account_dto(AccountDto self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_eq_settings_dto(
    EqSettingsDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_eq_state_dto(
    EqStateDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_track_dto(
    TrackDto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_cache_stats_dto(CacheStatsDto self, SseSerializer serializer);

  @protected
  void sse_encode_device_code_dto(DeviceCodeDto self, SseSerializer serializer);

  @protected
  void sse_encode_eq_band_dto(EqBandDto self, SseSerializer serializer);

  @protected
  void sse_encode_eq_mode_dto(EqModeDto self, SseSerializer serializer);

  @protected
  void sse_encode_eq_preset_dto(EqPresetDto self, SseSerializer serializer);

  @protected
  void sse_encode_eq_settings_dto(EqSettingsDto self, SseSerializer serializer);

  @protected
  void sse_encode_eq_state_dto(EqStateDto self, SseSerializer serializer);

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_filter_kind_dto(FilterKindDto self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_eq_band_dto(
    List<EqBandDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_eq_preset_dto(
    List<EqPresetDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_playlist_dto(
    List<PlaylistDto> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_f_32_strict(
    Float32List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_track_dto(List<TrackDto> self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_play_source_dto(PlaySourceDto self, SseSerializer serializer);

  @protected
  void sse_encode_playlist_dto(PlaylistDto self, SseSerializer serializer);

  @protected
  void sse_encode_stream_dto(StreamDto self, SseSerializer serializer);

  @protected
  void sse_encode_track_dto(TrackDto self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
