// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/cache.dart';
import 'api/eq.dart';
import 'api/wave.dart';
import 'api/yandex.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiYandexInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => 350985909;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_moth_amp',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<AccountDto> crateApiYandexAccount();

  Future<void> crateApiCacheCacheClear();

  Future<void> crateApiCacheCacheInit({
    required String dir,
    required int defaultLimitMb,
  });

  Future<void> crateApiCacheCacheSetLimit({required int limitMb});

  Future<CacheStatsDto> crateApiCacheCacheStats();

  double crateApiEqEqAutoPreamp({required EqSettingsDto settings});

  List<EqPresetDto> crateApiEqEqBuiltinPresets({required EqModeDto mode});

  double crateApiEqEqEffectivePreamp({required EqSettingsDto settings});

  EqSettingsDto crateApiEqEqFlat({required EqModeDto mode});

  Future<EqStateDto> crateApiEqEqLoad({required String path});

  EqSettingsDto crateApiEqEqParseAutoeq({required String text});

  Future<void> crateApiEqEqSave({
    required String path,
    required EqStateDto state,
  });

  String crateApiEqEqToFilter({required EqSettingsDto settings});

  EqSettingsDto crateApiEqEqWithMode({
    required EqSettingsDto settings,
    required EqModeDto mode,
  });

  Future<AccountDto> crateApiYandexFinishLogin();

  Future<void> crateApiYandexInitApp();

  Future<bool> crateApiYandexIsLoggedIn();

  Future<List<TrackDto>> crateApiYandexLikedTracks();

  Future<void> crateApiYandexLogout();

  Future<PlaySourceDto> crateApiCachePlaySource({required String trackId});

  Future<List<TrackDto>> crateApiYandexPlaylistTracks({required String id});

  Future<List<PlaylistDto>> crateApiYandexPlaylists();

  Future<List<TrackDto>> crateApiYandexSearch({required String query});

  Future<DeviceCodeDto> crateApiYandexStartLogin();

  Future<StreamDto> crateApiYandexStreamUrl({
    required String trackId,
    required bool lowQuality,
  });

  Future<List<TrackDto>> crateApiWaveWaveMore();

  Future<List<TrackDto>> crateApiWaveWaveStart({required bool learning});

  Future<void> crateApiWaveWaveStop();

  Future<void> crateApiWaveWaveTrackEnded({
    required String trackId,
    required double playedSecs,
    required bool skipped,
  });

  Future<void> crateApiWaveWaveTrackStarted({required String trackId});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<AccountDto> crateApiYandexAccount() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_account_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiYandexAccountConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiYandexAccountConstMeta =>
      const TaskConstMeta(debugName: "account", argNames: []);

  @override
  Future<void> crateApiCacheCacheClear() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCacheCacheClearConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCacheCacheClearConstMeta =>
      const TaskConstMeta(debugName: "cache_clear", argNames: []);

  @override
  Future<void> crateApiCacheCacheInit({
    required String dir,
    required int defaultLimitMb,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dir, serializer);
          sse_encode_u_32(defaultLimitMb, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCacheCacheInitConstMeta,
        argValues: [dir, defaultLimitMb],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCacheCacheInitConstMeta => const TaskConstMeta(
    debugName: "cache_init",
    argNames: ["dir", "defaultLimitMb"],
  );

  @override
  Future<void> crateApiCacheCacheSetLimit({required int limitMb}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(limitMb, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCacheCacheSetLimitConstMeta,
        argValues: [limitMb],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCacheCacheSetLimitConstMeta =>
      const TaskConstMeta(debugName: "cache_set_limit", argNames: ["limitMb"]);

  @override
  Future<CacheStatsDto> crateApiCacheCacheStats() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_cache_stats_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCacheCacheStatsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCacheCacheStatsConstMeta =>
      const TaskConstMeta(debugName: "cache_stats", argNames: []);

  @override
  double crateApiEqEqAutoPreamp({required EqSettingsDto settings}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_eq_settings_dto(settings, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_f_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEqEqAutoPreampConstMeta,
        argValues: [settings],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEqEqAutoPreampConstMeta =>
      const TaskConstMeta(debugName: "eq_auto_preamp", argNames: ["settings"]);

  @override
  List<EqPresetDto> crateApiEqEqBuiltinPresets({required EqModeDto mode}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_eq_mode_dto(mode, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_eq_preset_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEqEqBuiltinPresetsConstMeta,
        argValues: [mode],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEqEqBuiltinPresetsConstMeta =>
      const TaskConstMeta(debugName: "eq_builtin_presets", argNames: ["mode"]);

  @override
  double crateApiEqEqEffectivePreamp({required EqSettingsDto settings}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_eq_settings_dto(settings, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_f_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEqEqEffectivePreampConstMeta,
        argValues: [settings],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEqEqEffectivePreampConstMeta =>
      const TaskConstMeta(
        debugName: "eq_effective_preamp",
        argNames: ["settings"],
      );

  @override
  EqSettingsDto crateApiEqEqFlat({required EqModeDto mode}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_eq_mode_dto(mode, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_eq_settings_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEqEqFlatConstMeta,
        argValues: [mode],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEqEqFlatConstMeta =>
      const TaskConstMeta(debugName: "eq_flat", argNames: ["mode"]);

  @override
  Future<EqStateDto> crateApiEqEqLoad({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_eq_state_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiEqEqLoadConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEqEqLoadConstMeta =>
      const TaskConstMeta(debugName: "eq_load", argNames: ["path"]);

  @override
  EqSettingsDto crateApiEqEqParseAutoeq({required String text}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(text, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_eq_settings_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiEqEqParseAutoeqConstMeta,
        argValues: [text],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEqEqParseAutoeqConstMeta =>
      const TaskConstMeta(debugName: "eq_parse_autoeq", argNames: ["text"]);

  @override
  Future<void> crateApiEqEqSave({
    required String path,
    required EqStateDto state,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_box_autoadd_eq_state_dto(state, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiEqEqSaveConstMeta,
        argValues: [path, state],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEqEqSaveConstMeta =>
      const TaskConstMeta(debugName: "eq_save", argNames: ["path", "state"]);

  @override
  String crateApiEqEqToFilter({required EqSettingsDto settings}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_eq_settings_dto(settings, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEqEqToFilterConstMeta,
        argValues: [settings],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEqEqToFilterConstMeta =>
      const TaskConstMeta(debugName: "eq_to_filter", argNames: ["settings"]);

  @override
  EqSettingsDto crateApiEqEqWithMode({
    required EqSettingsDto settings,
    required EqModeDto mode,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_eq_settings_dto(settings, serializer);
          sse_encode_eq_mode_dto(mode, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_eq_settings_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEqEqWithModeConstMeta,
        argValues: [settings, mode],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEqEqWithModeConstMeta => const TaskConstMeta(
    debugName: "eq_with_mode",
    argNames: ["settings", "mode"],
  );

  @override
  Future<AccountDto> crateApiYandexFinishLogin() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_account_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiYandexFinishLoginConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiYandexFinishLoginConstMeta =>
      const TaskConstMeta(debugName: "finish_login", argNames: []);

  @override
  Future<void> crateApiYandexInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiYandexInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiYandexInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<bool> crateApiYandexIsLoggedIn() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiYandexIsLoggedInConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiYandexIsLoggedInConstMeta =>
      const TaskConstMeta(debugName: "is_logged_in", argNames: []);

  @override
  Future<List<TrackDto>> crateApiYandexLikedTracks() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_track_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiYandexLikedTracksConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiYandexLikedTracksConstMeta =>
      const TaskConstMeta(debugName: "liked_tracks", argNames: []);

  @override
  Future<void> crateApiYandexLogout() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiYandexLogoutConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiYandexLogoutConstMeta =>
      const TaskConstMeta(debugName: "logout", argNames: []);

  @override
  Future<PlaySourceDto> crateApiCachePlaySource({required String trackId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(trackId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_play_source_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCachePlaySourceConstMeta,
        argValues: [trackId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCachePlaySourceConstMeta =>
      const TaskConstMeta(debugName: "play_source", argNames: ["trackId"]);

  @override
  Future<List<TrackDto>> crateApiYandexPlaylistTracks({required String id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_track_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiYandexPlaylistTracksConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiYandexPlaylistTracksConstMeta =>
      const TaskConstMeta(debugName: "playlist_tracks", argNames: ["id"]);

  @override
  Future<List<PlaylistDto>> crateApiYandexPlaylists() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_playlist_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiYandexPlaylistsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiYandexPlaylistsConstMeta =>
      const TaskConstMeta(debugName: "playlists", argNames: []);

  @override
  Future<List<TrackDto>> crateApiYandexSearch({required String query}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(query, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_track_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiYandexSearchConstMeta,
        argValues: [query],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiYandexSearchConstMeta =>
      const TaskConstMeta(debugName: "search", argNames: ["query"]);

  @override
  Future<DeviceCodeDto> crateApiYandexStartLogin() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_device_code_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiYandexStartLoginConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiYandexStartLoginConstMeta =>
      const TaskConstMeta(debugName: "start_login", argNames: []);

  @override
  Future<StreamDto> crateApiYandexStreamUrl({
    required String trackId,
    required bool lowQuality,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(trackId, serializer);
          sse_encode_bool(lowQuality, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_stream_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiYandexStreamUrlConstMeta,
        argValues: [trackId, lowQuality],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiYandexStreamUrlConstMeta => const TaskConstMeta(
    debugName: "stream_url",
    argNames: ["trackId", "lowQuality"],
  );

  @override
  Future<List<TrackDto>> crateApiWaveWaveMore() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 26,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_track_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiWaveWaveMoreConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWaveWaveMoreConstMeta =>
      const TaskConstMeta(debugName: "wave_more", argNames: []);

  @override
  Future<List<TrackDto>> crateApiWaveWaveStart({required bool learning}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_bool(learning, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 27,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_track_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiWaveWaveStartConstMeta,
        argValues: [learning],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWaveWaveStartConstMeta =>
      const TaskConstMeta(debugName: "wave_start", argNames: ["learning"]);

  @override
  Future<void> crateApiWaveWaveStop() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 28,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiWaveWaveStopConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWaveWaveStopConstMeta =>
      const TaskConstMeta(debugName: "wave_stop", argNames: []);

  @override
  Future<void> crateApiWaveWaveTrackEnded({
    required String trackId,
    required double playedSecs,
    required bool skipped,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(trackId, serializer);
          sse_encode_f_64(playedSecs, serializer);
          sse_encode_bool(skipped, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 29,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiWaveWaveTrackEndedConstMeta,
        argValues: [trackId, playedSecs, skipped],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWaveWaveTrackEndedConstMeta => const TaskConstMeta(
    debugName: "wave_track_ended",
    argNames: ["trackId", "playedSecs", "skipped"],
  );

  @override
  Future<void> crateApiWaveWaveTrackStarted({required String trackId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(trackId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 30,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiWaveWaveTrackStartedConstMeta,
        argValues: [trackId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWaveWaveTrackStartedConstMeta =>
      const TaskConstMeta(
        debugName: "wave_track_started",
        argNames: ["trackId"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AccountDto dco_decode_account_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return AccountDto(
      uid: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      hasPlus: dco_decode_bool(arr[2]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  EqSettingsDto dco_decode_box_autoadd_eq_settings_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_eq_settings_dto(raw);
  }

  @protected
  EqStateDto dco_decode_box_autoadd_eq_state_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_eq_state_dto(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  CacheStatsDto dco_decode_cache_stats_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return CacheStatsDto(
      usedMb: dco_decode_f_64(arr[0]),
      limitMb: dco_decode_u_32(arr[1]),
      tracks: dco_decode_u_32(arr[2]),
    );
  }

  @protected
  DeviceCodeDto dco_decode_device_code_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return DeviceCodeDto(
      userCode: dco_decode_String(arr[0]),
      verificationUrl: dco_decode_String(arr[1]),
      expiresIn: dco_decode_u_32(arr[2]),
    );
  }

  @protected
  EqBandDto dco_decode_eq_band_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return EqBandDto(
      kind: dco_decode_filter_kind_dto(arr[0]),
      freqHz: dco_decode_f_32(arr[1]),
      gainDb: dco_decode_f_32(arr[2]),
      q: dco_decode_f_32(arr[3]),
    );
  }

  @protected
  EqModeDto dco_decode_eq_mode_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return EqModeDto.values[raw as int];
  }

  @protected
  EqPresetDto dco_decode_eq_preset_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return EqPresetDto(
      name: dco_decode_String(arr[0]),
      settings: dco_decode_eq_settings_dto(arr[1]),
    );
  }

  @protected
  EqSettingsDto dco_decode_eq_settings_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return EqSettingsDto(
      enabled: dco_decode_bool(arr[0]),
      mode: dco_decode_eq_mode_dto(arr[1]),
      preampDb: dco_decode_f_32(arr[2]),
      bands: dco_decode_list_eq_band_dto(arr[3]),
    );
  }

  @protected
  EqStateDto dco_decode_eq_state_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return EqStateDto(
      current: dco_decode_eq_settings_dto(arr[0]),
      userPresets: dco_decode_list_eq_preset_dto(arr[1]),
    );
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  FilterKindDto dco_decode_filter_kind_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return FilterKindDto.values[raw as int];
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<EqBandDto> dco_decode_list_eq_band_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_eq_band_dto).toList();
  }

  @protected
  List<EqPresetDto> dco_decode_list_eq_preset_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_eq_preset_dto).toList();
  }

  @protected
  List<PlaylistDto> dco_decode_list_playlist_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_playlist_dto).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<TrackDto> dco_decode_list_track_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_track_dto).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  PlaySourceDto dco_decode_play_source_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return PlaySourceDto(
      url: dco_decode_String(arr[0]),
      codec: dco_decode_String(arr[1]),
      bitrateKbps: dco_decode_opt_box_autoadd_u_32(arr[2]),
      isPreview: dco_decode_bool(arr[3]),
      cached: dco_decode_bool(arr[4]),
    );
  }

  @protected
  PlaylistDto dco_decode_playlist_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return PlaylistDto(
      id: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      trackCount: dco_decode_opt_box_autoadd_u_32(arr[2]),
    );
  }

  @protected
  StreamDto dco_decode_stream_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return StreamDto(
      url: dco_decode_String(arr[0]),
      codec: dco_decode_String(arr[1]),
      bitrateKbps: dco_decode_opt_box_autoadd_u_32(arr[2]),
      isPreview: dco_decode_bool(arr[3]),
    );
  }

  @protected
  TrackDto dco_decode_track_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return TrackDto(
      id: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      artists: dco_decode_String(arr[2]),
      album: dco_decode_opt_String(arr[3]),
      durationMs: dco_decode_opt_box_autoadd_u_32(arr[4]),
      available: dco_decode_bool(arr[5]),
      coverUrl: dco_decode_opt_String(arr[6]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AccountDto sse_decode_account_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_uid = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_hasPlus = sse_decode_bool(deserializer);
    return AccountDto(uid: var_uid, name: var_name, hasPlus: var_hasPlus);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  EqSettingsDto sse_decode_box_autoadd_eq_settings_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_eq_settings_dto(deserializer));
  }

  @protected
  EqStateDto sse_decode_box_autoadd_eq_state_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_eq_state_dto(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  CacheStatsDto sse_decode_cache_stats_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_usedMb = sse_decode_f_64(deserializer);
    var var_limitMb = sse_decode_u_32(deserializer);
    var var_tracks = sse_decode_u_32(deserializer);
    return CacheStatsDto(
      usedMb: var_usedMb,
      limitMb: var_limitMb,
      tracks: var_tracks,
    );
  }

  @protected
  DeviceCodeDto sse_decode_device_code_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_userCode = sse_decode_String(deserializer);
    var var_verificationUrl = sse_decode_String(deserializer);
    var var_expiresIn = sse_decode_u_32(deserializer);
    return DeviceCodeDto(
      userCode: var_userCode,
      verificationUrl: var_verificationUrl,
      expiresIn: var_expiresIn,
    );
  }

  @protected
  EqBandDto sse_decode_eq_band_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_filter_kind_dto(deserializer);
    var var_freqHz = sse_decode_f_32(deserializer);
    var var_gainDb = sse_decode_f_32(deserializer);
    var var_q = sse_decode_f_32(deserializer);
    return EqBandDto(
      kind: var_kind,
      freqHz: var_freqHz,
      gainDb: var_gainDb,
      q: var_q,
    );
  }

  @protected
  EqModeDto sse_decode_eq_mode_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return EqModeDto.values[inner];
  }

  @protected
  EqPresetDto sse_decode_eq_preset_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_settings = sse_decode_eq_settings_dto(deserializer);
    return EqPresetDto(name: var_name, settings: var_settings);
  }

  @protected
  EqSettingsDto sse_decode_eq_settings_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_enabled = sse_decode_bool(deserializer);
    var var_mode = sse_decode_eq_mode_dto(deserializer);
    var var_preampDb = sse_decode_f_32(deserializer);
    var var_bands = sse_decode_list_eq_band_dto(deserializer);
    return EqSettingsDto(
      enabled: var_enabled,
      mode: var_mode,
      preampDb: var_preampDb,
      bands: var_bands,
    );
  }

  @protected
  EqStateDto sse_decode_eq_state_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_current = sse_decode_eq_settings_dto(deserializer);
    var var_userPresets = sse_decode_list_eq_preset_dto(deserializer);
    return EqStateDto(current: var_current, userPresets: var_userPresets);
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  FilterKindDto sse_decode_filter_kind_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return FilterKindDto.values[inner];
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<EqBandDto> sse_decode_list_eq_band_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <EqBandDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_eq_band_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<EqPresetDto> sse_decode_list_eq_preset_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <EqPresetDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_eq_preset_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<PlaylistDto> sse_decode_list_playlist_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <PlaylistDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_playlist_dto(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<TrackDto> sse_decode_list_track_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TrackDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_track_dto(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlaySourceDto sse_decode_play_source_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_url = sse_decode_String(deserializer);
    var var_codec = sse_decode_String(deserializer);
    var var_bitrateKbps = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_isPreview = sse_decode_bool(deserializer);
    var var_cached = sse_decode_bool(deserializer);
    return PlaySourceDto(
      url: var_url,
      codec: var_codec,
      bitrateKbps: var_bitrateKbps,
      isPreview: var_isPreview,
      cached: var_cached,
    );
  }

  @protected
  PlaylistDto sse_decode_playlist_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_trackCount = sse_decode_opt_box_autoadd_u_32(deserializer);
    return PlaylistDto(
      id: var_id,
      title: var_title,
      trackCount: var_trackCount,
    );
  }

  @protected
  StreamDto sse_decode_stream_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_url = sse_decode_String(deserializer);
    var var_codec = sse_decode_String(deserializer);
    var var_bitrateKbps = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_isPreview = sse_decode_bool(deserializer);
    return StreamDto(
      url: var_url,
      codec: var_codec,
      bitrateKbps: var_bitrateKbps,
      isPreview: var_isPreview,
    );
  }

  @protected
  TrackDto sse_decode_track_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_artists = sse_decode_String(deserializer);
    var var_album = sse_decode_opt_String(deserializer);
    var var_durationMs = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_available = sse_decode_bool(deserializer);
    var var_coverUrl = sse_decode_opt_String(deserializer);
    return TrackDto(
      id: var_id,
      title: var_title,
      artists: var_artists,
      album: var_album,
      durationMs: var_durationMs,
      available: var_available,
      coverUrl: var_coverUrl,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_account_dto(AccountDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.uid, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_bool(self.hasPlus, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_eq_settings_dto(
    EqSettingsDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_eq_settings_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_eq_state_dto(
    EqStateDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_eq_state_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_cache_stats_dto(
    CacheStatsDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.usedMb, serializer);
    sse_encode_u_32(self.limitMb, serializer);
    sse_encode_u_32(self.tracks, serializer);
  }

  @protected
  void sse_encode_device_code_dto(
    DeviceCodeDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.userCode, serializer);
    sse_encode_String(self.verificationUrl, serializer);
    sse_encode_u_32(self.expiresIn, serializer);
  }

  @protected
  void sse_encode_eq_band_dto(EqBandDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_filter_kind_dto(self.kind, serializer);
    sse_encode_f_32(self.freqHz, serializer);
    sse_encode_f_32(self.gainDb, serializer);
    sse_encode_f_32(self.q, serializer);
  }

  @protected
  void sse_encode_eq_mode_dto(EqModeDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_eq_preset_dto(EqPresetDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_eq_settings_dto(self.settings, serializer);
  }

  @protected
  void sse_encode_eq_settings_dto(
    EqSettingsDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.enabled, serializer);
    sse_encode_eq_mode_dto(self.mode, serializer);
    sse_encode_f_32(self.preampDb, serializer);
    sse_encode_list_eq_band_dto(self.bands, serializer);
  }

  @protected
  void sse_encode_eq_state_dto(EqStateDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_eq_settings_dto(self.current, serializer);
    sse_encode_list_eq_preset_dto(self.userPresets, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_filter_kind_dto(
    FilterKindDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_eq_band_dto(
    List<EqBandDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_eq_band_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_eq_preset_dto(
    List<EqPresetDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_eq_preset_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_playlist_dto(
    List<PlaylistDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_playlist_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_track_dto(
    List<TrackDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_track_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_play_source_dto(
    PlaySourceDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.url, serializer);
    sse_encode_String(self.codec, serializer);
    sse_encode_opt_box_autoadd_u_32(self.bitrateKbps, serializer);
    sse_encode_bool(self.isPreview, serializer);
    sse_encode_bool(self.cached, serializer);
  }

  @protected
  void sse_encode_playlist_dto(PlaylistDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_opt_box_autoadd_u_32(self.trackCount, serializer);
  }

  @protected
  void sse_encode_stream_dto(StreamDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.url, serializer);
    sse_encode_String(self.codec, serializer);
    sse_encode_opt_box_autoadd_u_32(self.bitrateKbps, serializer);
    sse_encode_bool(self.isPreview, serializer);
  }

  @protected
  void sse_encode_track_dto(TrackDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.artists, serializer);
    sse_encode_opt_String(self.album, serializer);
    sse_encode_opt_box_autoadd_u_32(self.durationMs, serializer);
    sse_encode_bool(self.available, serializer);
    sse_encode_opt_String(self.coverUrl, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
