// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/cache.dart';
import 'api/eq.dart';
import 'api/s3.dart';
import 'api/wave.dart';
import 'api/yandex.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiYandexInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => -1261225551;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_moth_amp',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<AccountDto> crateApiYandexAccount();

  Future<List<TrackDto>> crateApiYandexAlbumTracks({required String id});

  Future<void> crateApiYandexAppInit({required String dataDir});

  Future<ArtistPageDto> crateApiYandexArtistPage({required String id});

  Future<List<TrackDto>> crateApiYandexArtistTracks({required String id});

  Future<int> crateApiCacheCacheBackfillMeta();

  Future<void> crateApiCacheCacheClear();

  Future<void> crateApiCacheCacheDownload({required TrackDto track});

  Future<void> crateApiCacheCacheInit({
    required String dir,
    required int defaultLimitMb,
  });

  Future<int> crateApiCacheCacheMirrorToS3();

  Future<void> crateApiCacheCachePlaceFolderCover({
    required String folder,
    required String coverUrl,
  });

  Future<void> crateApiCacheCachePlaceInFolder({
    required String trackId,
    required String folder,
  });

  Future<void> crateApiCacheCacheSetAuto({required bool enabled});

  Future<int> crateApiCacheCacheSetFolder({String? folder});

  Future<void> crateApiCacheCacheSetLimit({required int limitMb});

  Future<CacheStatsDto> crateApiCacheCacheStats();

  Future<List<String>> crateApiCacheCachedIds();

  Future<List<TrackDto>> crateApiCacheCachedTracks();

  double crateApiEqEqAutoPreamp({required EqSettingsDto settings});

  List<EqPresetDto> crateApiEqEqBuiltinPresets({required EqModeDto mode});

  double crateApiEqEqEffectivePreamp({required EqSettingsDto settings});

  EqSettingsDto crateApiEqEqFlat({required EqModeDto mode});

  EqSettingsDto crateApiEqEqParseAutoeq({required String text});

  Float32List crateApiEqEqResponse({
    required EqSettingsDto settings,
    required int points,
  });

  Future<void> crateApiEqEqSave({
    required String path,
    required EqStateDto state,
  });

  Future<EqStateDto> crateApiEqEqSync({required String path});

  String crateApiEqEqToFilter({required EqSettingsDto settings});

  EqSettingsDto crateApiEqEqWithMode({
    required EqSettingsDto settings,
    required EqModeDto mode,
  });

  Future<AccountDto> crateApiYandexFinishLogin();

  Future<void> crateApiYandexInitApp();

  Future<bool> crateApiYandexIsLoggedIn();

  Future<List<AlbumDto>> crateApiYandexLikedAlbums();

  Future<List<TrackDto>> crateApiYandexLikedTracks();

  Future<void> crateApiYandexLogout();

  Future<PlaySourceDto> crateApiCachePlaySource({required TrackDto track});

  Future<List<TrackDto>> crateApiYandexPlaylistTracks({
    required String id,
    String? ownerUid,
  });

  Future<List<PlaylistDto>> crateApiYandexPlaylists();

  Future<int> crateApiS3S3Connect({required S3ConfigDto config});

  Future<void> crateApiS3S3Disconnect();

  Future<S3StatusDto> crateApiS3S3Status();

  Future<S3SyncDto> crateApiCacheS3Sync();

  Future<List<TrackDto>> crateApiS3S3Tracks();

  Future<S3UploadResultDto> crateApiS3S3Upload({required List<String> paths});

  Future<SearchDto> crateApiYandexSearchAll({required String query});

  Future<DeviceCodeDto> crateApiYandexStartLogin();

  Future<List<TrackDto>> crateApiWaveWaveMore();

  Future<WaveSettingsDto> crateApiWaveWaveSettings();

  Future<List<TrackDto>> crateApiWaveWaveStart({
    required bool learning,
    required List<String> seeds,
  });

  Future<void> crateApiWaveWaveStop();

  Future<void> crateApiWaveWaveTrackEnded({
    required String trackId,
    required double playedSecs,
    required bool skipped,
  });

  Future<void> crateApiWaveWaveTrackStarted({required String trackId});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<AccountDto> crateApiYandexAccount() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_account_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiYandexAccountConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiYandexAccountConstMeta =>
      const TaskConstMeta(debugName: "account", argNames: []);

  @override
  Future<List<TrackDto>> crateApiYandexAlbumTracks({required String id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_track_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiYandexAlbumTracksConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiYandexAlbumTracksConstMeta =>
      const TaskConstMeta(debugName: "album_tracks", argNames: ["id"]);

  @override
  Future<void> crateApiYandexAppInit({required String dataDir}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dataDir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiYandexAppInitConstMeta,
        argValues: [dataDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiYandexAppInitConstMeta =>
      const TaskConstMeta(debugName: "app_init", argNames: ["dataDir"]);

  @override
  Future<ArtistPageDto> crateApiYandexArtistPage({required String id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_artist_page_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiYandexArtistPageConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiYandexArtistPageConstMeta =>
      const TaskConstMeta(debugName: "artist_page", argNames: ["id"]);

  @override
  Future<List<TrackDto>> crateApiYandexArtistTracks({required String id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_track_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiYandexArtistTracksConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiYandexArtistTracksConstMeta =>
      const TaskConstMeta(debugName: "artist_tracks", argNames: ["id"]);

  @override
  Future<int> crateApiCacheCacheBackfillMeta() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCacheCacheBackfillMetaConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCacheCacheBackfillMetaConstMeta =>
      const TaskConstMeta(debugName: "cache_backfill_meta", argNames: []);

  @override
  Future<void> crateApiCacheCacheClear() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCacheCacheClearConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCacheCacheClearConstMeta =>
      const TaskConstMeta(debugName: "cache_clear", argNames: []);

  @override
  Future<void> crateApiCacheCacheDownload({required TrackDto track}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_track_dto(track, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCacheCacheDownloadConstMeta,
        argValues: [track],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCacheCacheDownloadConstMeta =>
      const TaskConstMeta(debugName: "cache_download", argNames: ["track"]);

  @override
  Future<void> crateApiCacheCacheInit({
    required String dir,
    required int defaultLimitMb,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dir, serializer);
          sse_encode_u_32(defaultLimitMb, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCacheCacheInitConstMeta,
        argValues: [dir, defaultLimitMb],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCacheCacheInitConstMeta => const TaskConstMeta(
    debugName: "cache_init",
    argNames: ["dir", "defaultLimitMb"],
  );

  @override
  Future<int> crateApiCacheCacheMirrorToS3() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCacheCacheMirrorToS3ConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCacheCacheMirrorToS3ConstMeta =>
      const TaskConstMeta(debugName: "cache_mirror_to_s3", argNames: []);

  @override
  Future<void> crateApiCacheCachePlaceFolderCover({
    required String folder,
    required String coverUrl,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(folder, serializer);
          sse_encode_String(coverUrl, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCacheCachePlaceFolderCoverConstMeta,
        argValues: [folder, coverUrl],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCacheCachePlaceFolderCoverConstMeta =>
      const TaskConstMeta(
        debugName: "cache_place_folder_cover",
        argNames: ["folder", "coverUrl"],
      );

  @override
  Future<void> crateApiCacheCachePlaceInFolder({
    required String trackId,
    required String folder,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(trackId, serializer);
          sse_encode_String(folder, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCacheCachePlaceInFolderConstMeta,
        argValues: [trackId, folder],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCacheCachePlaceInFolderConstMeta =>
      const TaskConstMeta(
        debugName: "cache_place_in_folder",
        argNames: ["trackId", "folder"],
      );

  @override
  Future<void> crateApiCacheCacheSetAuto({required bool enabled}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_bool(enabled, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCacheCacheSetAutoConstMeta,
        argValues: [enabled],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCacheCacheSetAutoConstMeta =>
      const TaskConstMeta(debugName: "cache_set_auto", argNames: ["enabled"]);

  @override
  Future<int> crateApiCacheCacheSetFolder({String? folder}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_String(folder, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCacheCacheSetFolderConstMeta,
        argValues: [folder],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCacheCacheSetFolderConstMeta =>
      const TaskConstMeta(debugName: "cache_set_folder", argNames: ["folder"]);

  @override
  Future<void> crateApiCacheCacheSetLimit({required int limitMb}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(limitMb, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCacheCacheSetLimitConstMeta,
        argValues: [limitMb],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCacheCacheSetLimitConstMeta =>
      const TaskConstMeta(debugName: "cache_set_limit", argNames: ["limitMb"]);

  @override
  Future<CacheStatsDto> crateApiCacheCacheStats() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_cache_stats_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCacheCacheStatsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCacheCacheStatsConstMeta =>
      const TaskConstMeta(debugName: "cache_stats", argNames: []);

  @override
  Future<List<String>> crateApiCacheCachedIds() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCacheCachedIdsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCacheCachedIdsConstMeta =>
      const TaskConstMeta(debugName: "cached_ids", argNames: []);

  @override
  Future<List<TrackDto>> crateApiCacheCachedTracks() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_track_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCacheCachedTracksConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCacheCachedTracksConstMeta =>
      const TaskConstMeta(debugName: "cached_tracks", argNames: []);

  @override
  double crateApiEqEqAutoPreamp({required EqSettingsDto settings}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_eq_settings_dto(settings, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_f_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEqEqAutoPreampConstMeta,
        argValues: [settings],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEqEqAutoPreampConstMeta =>
      const TaskConstMeta(debugName: "eq_auto_preamp", argNames: ["settings"]);

  @override
  List<EqPresetDto> crateApiEqEqBuiltinPresets({required EqModeDto mode}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_eq_mode_dto(mode, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 20)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_eq_preset_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEqEqBuiltinPresetsConstMeta,
        argValues: [mode],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEqEqBuiltinPresetsConstMeta =>
      const TaskConstMeta(debugName: "eq_builtin_presets", argNames: ["mode"]);

  @override
  double crateApiEqEqEffectivePreamp({required EqSettingsDto settings}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_eq_settings_dto(settings, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 21)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_f_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEqEqEffectivePreampConstMeta,
        argValues: [settings],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEqEqEffectivePreampConstMeta =>
      const TaskConstMeta(
        debugName: "eq_effective_preamp",
        argNames: ["settings"],
      );

  @override
  EqSettingsDto crateApiEqEqFlat({required EqModeDto mode}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_eq_mode_dto(mode, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 22)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_eq_settings_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEqEqFlatConstMeta,
        argValues: [mode],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEqEqFlatConstMeta =>
      const TaskConstMeta(debugName: "eq_flat", argNames: ["mode"]);

  @override
  EqSettingsDto crateApiEqEqParseAutoeq({required String text}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(text, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 23)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_eq_settings_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiEqEqParseAutoeqConstMeta,
        argValues: [text],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEqEqParseAutoeqConstMeta =>
      const TaskConstMeta(debugName: "eq_parse_autoeq", argNames: ["text"]);

  @override
  Float32List crateApiEqEqResponse({
    required EqSettingsDto settings,
    required int points,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_eq_settings_dto(settings, serializer);
          sse_encode_u_32(points, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 24)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_f_32_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEqEqResponseConstMeta,
        argValues: [settings, points],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEqEqResponseConstMeta => const TaskConstMeta(
    debugName: "eq_response",
    argNames: ["settings", "points"],
  );

  @override
  Future<void> crateApiEqEqSave({
    required String path,
    required EqStateDto state,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_box_autoadd_eq_state_dto(state, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiEqEqSaveConstMeta,
        argValues: [path, state],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEqEqSaveConstMeta =>
      const TaskConstMeta(debugName: "eq_save", argNames: ["path", "state"]);

  @override
  Future<EqStateDto> crateApiEqEqSync({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 26,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_eq_state_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiEqEqSyncConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEqEqSyncConstMeta =>
      const TaskConstMeta(debugName: "eq_sync", argNames: ["path"]);

  @override
  String crateApiEqEqToFilter({required EqSettingsDto settings}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_eq_settings_dto(settings, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 27)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEqEqToFilterConstMeta,
        argValues: [settings],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEqEqToFilterConstMeta =>
      const TaskConstMeta(debugName: "eq_to_filter", argNames: ["settings"]);

  @override
  EqSettingsDto crateApiEqEqWithMode({
    required EqSettingsDto settings,
    required EqModeDto mode,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_eq_settings_dto(settings, serializer);
          sse_encode_eq_mode_dto(mode, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 28)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_eq_settings_dto,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEqEqWithModeConstMeta,
        argValues: [settings, mode],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEqEqWithModeConstMeta => const TaskConstMeta(
    debugName: "eq_with_mode",
    argNames: ["settings", "mode"],
  );

  @override
  Future<AccountDto> crateApiYandexFinishLogin() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 29,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_account_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiYandexFinishLoginConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiYandexFinishLoginConstMeta =>
      const TaskConstMeta(debugName: "finish_login", argNames: []);

  @override
  Future<void> crateApiYandexInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 30,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiYandexInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiYandexInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<bool> crateApiYandexIsLoggedIn() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 31,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiYandexIsLoggedInConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiYandexIsLoggedInConstMeta =>
      const TaskConstMeta(debugName: "is_logged_in", argNames: []);

  @override
  Future<List<AlbumDto>> crateApiYandexLikedAlbums() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 32,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_album_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiYandexLikedAlbumsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiYandexLikedAlbumsConstMeta =>
      const TaskConstMeta(debugName: "liked_albums", argNames: []);

  @override
  Future<List<TrackDto>> crateApiYandexLikedTracks() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 33,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_track_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiYandexLikedTracksConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiYandexLikedTracksConstMeta =>
      const TaskConstMeta(debugName: "liked_tracks", argNames: []);

  @override
  Future<void> crateApiYandexLogout() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 34,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiYandexLogoutConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiYandexLogoutConstMeta =>
      const TaskConstMeta(debugName: "logout", argNames: []);

  @override
  Future<PlaySourceDto> crateApiCachePlaySource({required TrackDto track}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_track_dto(track, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 35,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_play_source_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCachePlaySourceConstMeta,
        argValues: [track],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCachePlaySourceConstMeta =>
      const TaskConstMeta(debugName: "play_source", argNames: ["track"]);

  @override
  Future<List<TrackDto>> crateApiYandexPlaylistTracks({
    required String id,
    String? ownerUid,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          sse_encode_opt_String(ownerUid, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 36,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_track_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiYandexPlaylistTracksConstMeta,
        argValues: [id, ownerUid],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiYandexPlaylistTracksConstMeta =>
      const TaskConstMeta(
        debugName: "playlist_tracks",
        argNames: ["id", "ownerUid"],
      );

  @override
  Future<List<PlaylistDto>> crateApiYandexPlaylists() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 37,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_playlist_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiYandexPlaylistsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiYandexPlaylistsConstMeta =>
      const TaskConstMeta(debugName: "playlists", argNames: []);

  @override
  Future<int> crateApiS3S3Connect({required S3ConfigDto config}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_s_3_config_dto(config, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 38,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiS3S3ConnectConstMeta,
        argValues: [config],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiS3S3ConnectConstMeta =>
      const TaskConstMeta(debugName: "s3_connect", argNames: ["config"]);

  @override
  Future<void> crateApiS3S3Disconnect() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 39,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiS3S3DisconnectConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiS3S3DisconnectConstMeta =>
      const TaskConstMeta(debugName: "s3_disconnect", argNames: []);

  @override
  Future<S3StatusDto> crateApiS3S3Status() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 40,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_s_3_status_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiS3S3StatusConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiS3S3StatusConstMeta =>
      const TaskConstMeta(debugName: "s3_status", argNames: []);

  @override
  Future<S3SyncDto> crateApiCacheS3Sync() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 41,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_s_3_sync_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCacheS3SyncConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCacheS3SyncConstMeta =>
      const TaskConstMeta(debugName: "s3_sync", argNames: []);

  @override
  Future<List<TrackDto>> crateApiS3S3Tracks() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 42,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_track_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiS3S3TracksConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiS3S3TracksConstMeta =>
      const TaskConstMeta(debugName: "s3_tracks", argNames: []);

  @override
  Future<S3UploadResultDto> crateApiS3S3Upload({required List<String> paths}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_String(paths, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 43,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_s_3_upload_result_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiS3S3UploadConstMeta,
        argValues: [paths],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiS3S3UploadConstMeta =>
      const TaskConstMeta(debugName: "s3_upload", argNames: ["paths"]);

  @override
  Future<SearchDto> crateApiYandexSearchAll({required String query}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(query, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 44,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_search_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiYandexSearchAllConstMeta,
        argValues: [query],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiYandexSearchAllConstMeta =>
      const TaskConstMeta(debugName: "search_all", argNames: ["query"]);

  @override
  Future<DeviceCodeDto> crateApiYandexStartLogin() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 45,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_device_code_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiYandexStartLoginConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiYandexStartLoginConstMeta =>
      const TaskConstMeta(debugName: "start_login", argNames: []);

  @override
  Future<List<TrackDto>> crateApiWaveWaveMore() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 46,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_track_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiWaveWaveMoreConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWaveWaveMoreConstMeta =>
      const TaskConstMeta(debugName: "wave_more", argNames: []);

  @override
  Future<WaveSettingsDto> crateApiWaveWaveSettings() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 47,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_wave_settings_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiWaveWaveSettingsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWaveWaveSettingsConstMeta =>
      const TaskConstMeta(debugName: "wave_settings", argNames: []);

  @override
  Future<List<TrackDto>> crateApiWaveWaveStart({
    required bool learning,
    required List<String> seeds,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_bool(learning, serializer);
          sse_encode_list_String(seeds, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 48,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_track_dto,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiWaveWaveStartConstMeta,
        argValues: [learning, seeds],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWaveWaveStartConstMeta => const TaskConstMeta(
    debugName: "wave_start",
    argNames: ["learning", "seeds"],
  );

  @override
  Future<void> crateApiWaveWaveStop() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 49,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiWaveWaveStopConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWaveWaveStopConstMeta =>
      const TaskConstMeta(debugName: "wave_stop", argNames: []);

  @override
  Future<void> crateApiWaveWaveTrackEnded({
    required String trackId,
    required double playedSecs,
    required bool skipped,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(trackId, serializer);
          sse_encode_f_64(playedSecs, serializer);
          sse_encode_bool(skipped, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 50,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiWaveWaveTrackEndedConstMeta,
        argValues: [trackId, playedSecs, skipped],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWaveWaveTrackEndedConstMeta => const TaskConstMeta(
    debugName: "wave_track_ended",
    argNames: ["trackId", "playedSecs", "skipped"],
  );

  @override
  Future<void> crateApiWaveWaveTrackStarted({required String trackId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(trackId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 51,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiWaveWaveTrackStartedConstMeta,
        argValues: [trackId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWaveWaveTrackStartedConstMeta =>
      const TaskConstMeta(
        debugName: "wave_track_started",
        argNames: ["trackId"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AccountDto dco_decode_account_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return AccountDto(
      name: dco_decode_String(arr[0]),
      hasPlus: dco_decode_bool(arr[1]),
    );
  }

  @protected
  AlbumDto dco_decode_album_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return AlbumDto(
      id: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      artists: dco_decode_String(arr[2]),
      year: dco_decode_opt_box_autoadd_u_32(arr[3]),
      coverUrl: dco_decode_opt_String(arr[4]),
      trackCount: dco_decode_opt_box_autoadd_u_32(arr[5]),
      folderName: dco_decode_String(arr[6]),
    );
  }

  @protected
  ArtistDto dco_decode_artist_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ArtistDto(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      coverUrl: dco_decode_opt_String(arr[2]),
    );
  }

  @protected
  ArtistPageDto dco_decode_artist_page_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return ArtistPageDto(
      artist: dco_decode_artist_dto(arr[0]),
      popularTracks: dco_decode_list_track_dto(arr[1]),
      albums: dco_decode_list_album_dto(arr[2]),
      alsoAlbums: dco_decode_list_album_dto(arr[3]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  EqSettingsDto dco_decode_box_autoadd_eq_settings_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_eq_settings_dto(raw);
  }

  @protected
  EqStateDto dco_decode_box_autoadd_eq_state_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_eq_state_dto(raw);
  }

  @protected
  S3ConfigDto dco_decode_box_autoadd_s_3_config_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_s_3_config_dto(raw);
  }

  @protected
  TrackDto dco_decode_box_autoadd_track_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_track_dto(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  CacheStatsDto dco_decode_cache_stats_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return CacheStatsDto(
      usedMb: dco_decode_f_64(arr[0]),
      limitMb: dco_decode_u_32(arr[1]),
      tracks: dco_decode_u_32(arr[2]),
      autoCache: dco_decode_bool(arr[3]),
      folder: dco_decode_String(arr[4]),
      customFolder: dco_decode_bool(arr[5]),
    );
  }

  @protected
  DeviceCodeDto dco_decode_device_code_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return DeviceCodeDto(
      userCode: dco_decode_String(arr[0]),
      verificationUrl: dco_decode_String(arr[1]),
      expiresIn: dco_decode_u_32(arr[2]),
    );
  }

  @protected
  EqBandDto dco_decode_eq_band_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return EqBandDto(
      kind: dco_decode_filter_kind_dto(arr[0]),
      freqHz: dco_decode_f_32(arr[1]),
      gainDb: dco_decode_f_32(arr[2]),
      q: dco_decode_f_32(arr[3]),
    );
  }

  @protected
  EqModeDto dco_decode_eq_mode_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return EqModeDto.values[raw as int];
  }

  @protected
  EqPresetDto dco_decode_eq_preset_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return EqPresetDto(
      name: dco_decode_String(arr[0]),
      settings: dco_decode_eq_settings_dto(arr[1]),
    );
  }

  @protected
  EqSettingsDto dco_decode_eq_settings_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return EqSettingsDto(
      enabled: dco_decode_bool(arr[0]),
      mode: dco_decode_eq_mode_dto(arr[1]),
      preampDb: dco_decode_f_32(arr[2]),
      bands: dco_decode_list_eq_band_dto(arr[3]),
    );
  }

  @protected
  EqStateDto dco_decode_eq_state_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return EqStateDto(
      current: dco_decode_eq_settings_dto(arr[0]),
      userPresets: dco_decode_list_eq_preset_dto(arr[1]),
    );
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  FilterKindDto dco_decode_filter_kind_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return FilterKindDto.values[raw as int];
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<AlbumDto> dco_decode_list_album_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_album_dto).toList();
  }

  @protected
  List<ArtistDto> dco_decode_list_artist_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_artist_dto).toList();
  }

  @protected
  List<EqBandDto> dco_decode_list_eq_band_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_eq_band_dto).toList();
  }

  @protected
  List<EqPresetDto> dco_decode_list_eq_preset_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_eq_preset_dto).toList();
  }

  @protected
  List<PlaylistDto> dco_decode_list_playlist_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_playlist_dto).toList();
  }

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Float32List;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<TrackDto> dco_decode_list_track_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_track_dto).toList();
  }

  @protected
  List<WaveGroupDto> dco_decode_list_wave_group_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_wave_group_dto).toList();
  }

  @protected
  List<WaveOptionDto> dco_decode_list_wave_option_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_wave_option_dto).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  PlaySourceDto dco_decode_play_source_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return PlaySourceDto(
      url: dco_decode_String(arr[0]),
      codec: dco_decode_String(arr[1]),
      bitrateKbps: dco_decode_opt_box_autoadd_u_32(arr[2]),
      isPreview: dco_decode_bool(arr[3]),
      cached: dco_decode_bool(arr[4]),
    );
  }

  @protected
  PlaylistDto dco_decode_playlist_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return PlaylistDto(
      id: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      trackCount: dco_decode_opt_box_autoadd_u_32(arr[2]),
      coverUrl: dco_decode_opt_String(arr[3]),
      ownerUid: dco_decode_opt_String(arr[4]),
    );
  }

  @protected
  S3ConfigDto dco_decode_s_3_config_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return S3ConfigDto(
      endpoint: dco_decode_String(arr[0]),
      region: dco_decode_String(arr[1]),
      bucket: dco_decode_String(arr[2]),
      accessKey: dco_decode_String(arr[3]),
      secretKey: dco_decode_String(arr[4]),
      pathStyle: dco_decode_bool(arr[5]),
    );
  }

  @protected
  S3StatusDto dco_decode_s_3_status_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return S3StatusDto(
      connected: dco_decode_bool(arr[0]),
      endpoint: dco_decode_String(arr[1]),
      region: dco_decode_String(arr[2]),
      bucket: dco_decode_String(arr[3]),
      accessKey: dco_decode_String(arr[4]),
      pathStyle: dco_decode_bool(arr[5]),
    );
  }

  @protected
  S3SyncDto dco_decode_s_3_sync_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return S3SyncDto(
      uploaded: dco_decode_u_32(arr[0]),
      found: dco_decode_u_32(arr[1]),
      removed: dco_decode_u_32(arr[2]),
    );
  }

  @protected
  S3UploadResultDto dco_decode_s_3_upload_result_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return S3UploadResultDto(
      uploaded: dco_decode_u_32(arr[0]),
      failed: dco_decode_list_String(arr[1]),
    );
  }

  @protected
  SearchDto dco_decode_search_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return SearchDto(
      best: dco_decode_opt_String(arr[0]),
      artists: dco_decode_list_artist_dto(arr[1]),
      albums: dco_decode_list_album_dto(arr[2]),
      playlists: dco_decode_list_playlist_dto(arr[3]),
      tracks: dco_decode_list_track_dto(arr[4]),
    );
  }

  @protected
  TrackDto dco_decode_track_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return TrackDto(
      id: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      artists: dco_decode_String(arr[2]),
      artistNames: dco_decode_list_String(arr[3]),
      album: dco_decode_opt_String(arr[4]),
      year: dco_decode_opt_box_autoadd_u_32(arr[5]),
      durationMs: dco_decode_opt_box_autoadd_u_32(arr[6]),
      available: dco_decode_bool(arr[7]),
      coverUrl: dco_decode_opt_String(arr[8]),
      source: dco_decode_String(arr[9]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  WaveGroupDto dco_decode_wave_group_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return WaveGroupDto(
      name: dco_decode_String(arr[0]),
      options: dco_decode_list_wave_option_dto(arr[1]),
    );
  }

  @protected
  WaveOptionDto dco_decode_wave_option_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return WaveOptionDto(
      name: dco_decode_String(arr[0]),
      seed: dco_decode_String(arr[1]),
      isDefault: dco_decode_bool(arr[2]),
    );
  }

  @protected
  WaveSettingsDto dco_decode_wave_settings_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return WaveSettingsDto(
      activities: dco_decode_list_wave_option_dto(arr[0]),
      groups: dco_decode_list_wave_group_dto(arr[1]),
    );
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AccountDto sse_decode_account_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_hasPlus = sse_decode_bool(deserializer);
    return AccountDto(name: var_name, hasPlus: var_hasPlus);
  }

  @protected
  AlbumDto sse_decode_album_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_artists = sse_decode_String(deserializer);
    var var_year = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_coverUrl = sse_decode_opt_String(deserializer);
    var var_trackCount = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_folderName = sse_decode_String(deserializer);
    return AlbumDto(
      id: var_id,
      title: var_title,
      artists: var_artists,
      year: var_year,
      coverUrl: var_coverUrl,
      trackCount: var_trackCount,
      folderName: var_folderName,
    );
  }

  @protected
  ArtistDto sse_decode_artist_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_coverUrl = sse_decode_opt_String(deserializer);
    return ArtistDto(id: var_id, name: var_name, coverUrl: var_coverUrl);
  }

  @protected
  ArtistPageDto sse_decode_artist_page_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_artist = sse_decode_artist_dto(deserializer);
    var var_popularTracks = sse_decode_list_track_dto(deserializer);
    var var_albums = sse_decode_list_album_dto(deserializer);
    var var_alsoAlbums = sse_decode_list_album_dto(deserializer);
    return ArtistPageDto(
      artist: var_artist,
      popularTracks: var_popularTracks,
      albums: var_albums,
      alsoAlbums: var_alsoAlbums,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  EqSettingsDto sse_decode_box_autoadd_eq_settings_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_eq_settings_dto(deserializer));
  }

  @protected
  EqStateDto sse_decode_box_autoadd_eq_state_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_eq_state_dto(deserializer));
  }

  @protected
  S3ConfigDto sse_decode_box_autoadd_s_3_config_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_s_3_config_dto(deserializer));
  }

  @protected
  TrackDto sse_decode_box_autoadd_track_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_track_dto(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  CacheStatsDto sse_decode_cache_stats_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_usedMb = sse_decode_f_64(deserializer);
    var var_limitMb = sse_decode_u_32(deserializer);
    var var_tracks = sse_decode_u_32(deserializer);
    var var_autoCache = sse_decode_bool(deserializer);
    var var_folder = sse_decode_String(deserializer);
    var var_customFolder = sse_decode_bool(deserializer);
    return CacheStatsDto(
      usedMb: var_usedMb,
      limitMb: var_limitMb,
      tracks: var_tracks,
      autoCache: var_autoCache,
      folder: var_folder,
      customFolder: var_customFolder,
    );
  }

  @protected
  DeviceCodeDto sse_decode_device_code_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_userCode = sse_decode_String(deserializer);
    var var_verificationUrl = sse_decode_String(deserializer);
    var var_expiresIn = sse_decode_u_32(deserializer);
    return DeviceCodeDto(
      userCode: var_userCode,
      verificationUrl: var_verificationUrl,
      expiresIn: var_expiresIn,
    );
  }

  @protected
  EqBandDto sse_decode_eq_band_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_filter_kind_dto(deserializer);
    var var_freqHz = sse_decode_f_32(deserializer);
    var var_gainDb = sse_decode_f_32(deserializer);
    var var_q = sse_decode_f_32(deserializer);
    return EqBandDto(
      kind: var_kind,
      freqHz: var_freqHz,
      gainDb: var_gainDb,
      q: var_q,
    );
  }

  @protected
  EqModeDto sse_decode_eq_mode_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return EqModeDto.values[inner];
  }

  @protected
  EqPresetDto sse_decode_eq_preset_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_settings = sse_decode_eq_settings_dto(deserializer);
    return EqPresetDto(name: var_name, settings: var_settings);
  }

  @protected
  EqSettingsDto sse_decode_eq_settings_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_enabled = sse_decode_bool(deserializer);
    var var_mode = sse_decode_eq_mode_dto(deserializer);
    var var_preampDb = sse_decode_f_32(deserializer);
    var var_bands = sse_decode_list_eq_band_dto(deserializer);
    return EqSettingsDto(
      enabled: var_enabled,
      mode: var_mode,
      preampDb: var_preampDb,
      bands: var_bands,
    );
  }

  @protected
  EqStateDto sse_decode_eq_state_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_current = sse_decode_eq_settings_dto(deserializer);
    var var_userPresets = sse_decode_list_eq_preset_dto(deserializer);
    return EqStateDto(current: var_current, userPresets: var_userPresets);
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  FilterKindDto sse_decode_filter_kind_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return FilterKindDto.values[inner];
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<AlbumDto> sse_decode_list_album_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <AlbumDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_album_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<ArtistDto> sse_decode_list_artist_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ArtistDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_artist_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<EqBandDto> sse_decode_list_eq_band_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <EqBandDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_eq_band_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<EqPresetDto> sse_decode_list_eq_preset_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <EqPresetDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_eq_preset_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<PlaylistDto> sse_decode_list_playlist_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <PlaylistDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_playlist_dto(deserializer));
    }
    return ans_;
  }

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat32List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<TrackDto> sse_decode_list_track_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TrackDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_track_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<WaveGroupDto> sse_decode_list_wave_group_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <WaveGroupDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_wave_group_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<WaveOptionDto> sse_decode_list_wave_option_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <WaveOptionDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_wave_option_dto(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlaySourceDto sse_decode_play_source_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_url = sse_decode_String(deserializer);
    var var_codec = sse_decode_String(deserializer);
    var var_bitrateKbps = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_isPreview = sse_decode_bool(deserializer);
    var var_cached = sse_decode_bool(deserializer);
    return PlaySourceDto(
      url: var_url,
      codec: var_codec,
      bitrateKbps: var_bitrateKbps,
      isPreview: var_isPreview,
      cached: var_cached,
    );
  }

  @protected
  PlaylistDto sse_decode_playlist_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_trackCount = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_coverUrl = sse_decode_opt_String(deserializer);
    var var_ownerUid = sse_decode_opt_String(deserializer);
    return PlaylistDto(
      id: var_id,
      title: var_title,
      trackCount: var_trackCount,
      coverUrl: var_coverUrl,
      ownerUid: var_ownerUid,
    );
  }

  @protected
  S3ConfigDto sse_decode_s_3_config_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_endpoint = sse_decode_String(deserializer);
    var var_region = sse_decode_String(deserializer);
    var var_bucket = sse_decode_String(deserializer);
    var var_accessKey = sse_decode_String(deserializer);
    var var_secretKey = sse_decode_String(deserializer);
    var var_pathStyle = sse_decode_bool(deserializer);
    return S3ConfigDto(
      endpoint: var_endpoint,
      region: var_region,
      bucket: var_bucket,
      accessKey: var_accessKey,
      secretKey: var_secretKey,
      pathStyle: var_pathStyle,
    );
  }

  @protected
  S3StatusDto sse_decode_s_3_status_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_connected = sse_decode_bool(deserializer);
    var var_endpoint = sse_decode_String(deserializer);
    var var_region = sse_decode_String(deserializer);
    var var_bucket = sse_decode_String(deserializer);
    var var_accessKey = sse_decode_String(deserializer);
    var var_pathStyle = sse_decode_bool(deserializer);
    return S3StatusDto(
      connected: var_connected,
      endpoint: var_endpoint,
      region: var_region,
      bucket: var_bucket,
      accessKey: var_accessKey,
      pathStyle: var_pathStyle,
    );
  }

  @protected
  S3SyncDto sse_decode_s_3_sync_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_uploaded = sse_decode_u_32(deserializer);
    var var_found = sse_decode_u_32(deserializer);
    var var_removed = sse_decode_u_32(deserializer);
    return S3SyncDto(
      uploaded: var_uploaded,
      found: var_found,
      removed: var_removed,
    );
  }

  @protected
  S3UploadResultDto sse_decode_s_3_upload_result_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_uploaded = sse_decode_u_32(deserializer);
    var var_failed = sse_decode_list_String(deserializer);
    return S3UploadResultDto(uploaded: var_uploaded, failed: var_failed);
  }

  @protected
  SearchDto sse_decode_search_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_best = sse_decode_opt_String(deserializer);
    var var_artists = sse_decode_list_artist_dto(deserializer);
    var var_albums = sse_decode_list_album_dto(deserializer);
    var var_playlists = sse_decode_list_playlist_dto(deserializer);
    var var_tracks = sse_decode_list_track_dto(deserializer);
    return SearchDto(
      best: var_best,
      artists: var_artists,
      albums: var_albums,
      playlists: var_playlists,
      tracks: var_tracks,
    );
  }

  @protected
  TrackDto sse_decode_track_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_artists = sse_decode_String(deserializer);
    var var_artistNames = sse_decode_list_String(deserializer);
    var var_album = sse_decode_opt_String(deserializer);
    var var_year = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_durationMs = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_available = sse_decode_bool(deserializer);
    var var_coverUrl = sse_decode_opt_String(deserializer);
    var var_source = sse_decode_String(deserializer);
    return TrackDto(
      id: var_id,
      title: var_title,
      artists: var_artists,
      artistNames: var_artistNames,
      album: var_album,
      year: var_year,
      durationMs: var_durationMs,
      available: var_available,
      coverUrl: var_coverUrl,
      source: var_source,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  WaveGroupDto sse_decode_wave_group_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_options = sse_decode_list_wave_option_dto(deserializer);
    return WaveGroupDto(name: var_name, options: var_options);
  }

  @protected
  WaveOptionDto sse_decode_wave_option_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_seed = sse_decode_String(deserializer);
    var var_isDefault = sse_decode_bool(deserializer);
    return WaveOptionDto(
      name: var_name,
      seed: var_seed,
      isDefault: var_isDefault,
    );
  }

  @protected
  WaveSettingsDto sse_decode_wave_settings_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_activities = sse_decode_list_wave_option_dto(deserializer);
    var var_groups = sse_decode_list_wave_group_dto(deserializer);
    return WaveSettingsDto(activities: var_activities, groups: var_groups);
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_account_dto(AccountDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_bool(self.hasPlus, serializer);
  }

  @protected
  void sse_encode_album_dto(AlbumDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.artists, serializer);
    sse_encode_opt_box_autoadd_u_32(self.year, serializer);
    sse_encode_opt_String(self.coverUrl, serializer);
    sse_encode_opt_box_autoadd_u_32(self.trackCount, serializer);
    sse_encode_String(self.folderName, serializer);
  }

  @protected
  void sse_encode_artist_dto(ArtistDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_opt_String(self.coverUrl, serializer);
  }

  @protected
  void sse_encode_artist_page_dto(
    ArtistPageDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_artist_dto(self.artist, serializer);
    sse_encode_list_track_dto(self.popularTracks, serializer);
    sse_encode_list_album_dto(self.albums, serializer);
    sse_encode_list_album_dto(self.alsoAlbums, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_eq_settings_dto(
    EqSettingsDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_eq_settings_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_eq_state_dto(
    EqStateDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_eq_state_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_s_3_config_dto(
    S3ConfigDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_s_3_config_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_track_dto(
    TrackDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_track_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_cache_stats_dto(
    CacheStatsDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.usedMb, serializer);
    sse_encode_u_32(self.limitMb, serializer);
    sse_encode_u_32(self.tracks, serializer);
    sse_encode_bool(self.autoCache, serializer);
    sse_encode_String(self.folder, serializer);
    sse_encode_bool(self.customFolder, serializer);
  }

  @protected
  void sse_encode_device_code_dto(
    DeviceCodeDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.userCode, serializer);
    sse_encode_String(self.verificationUrl, serializer);
    sse_encode_u_32(self.expiresIn, serializer);
  }

  @protected
  void sse_encode_eq_band_dto(EqBandDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_filter_kind_dto(self.kind, serializer);
    sse_encode_f_32(self.freqHz, serializer);
    sse_encode_f_32(self.gainDb, serializer);
    sse_encode_f_32(self.q, serializer);
  }

  @protected
  void sse_encode_eq_mode_dto(EqModeDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_eq_preset_dto(EqPresetDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_eq_settings_dto(self.settings, serializer);
  }

  @protected
  void sse_encode_eq_settings_dto(
    EqSettingsDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.enabled, serializer);
    sse_encode_eq_mode_dto(self.mode, serializer);
    sse_encode_f_32(self.preampDb, serializer);
    sse_encode_list_eq_band_dto(self.bands, serializer);
  }

  @protected
  void sse_encode_eq_state_dto(EqStateDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_eq_settings_dto(self.current, serializer);
    sse_encode_list_eq_preset_dto(self.userPresets, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_filter_kind_dto(
    FilterKindDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_album_dto(
    List<AlbumDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_album_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_artist_dto(
    List<ArtistDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_artist_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_eq_band_dto(
    List<EqBandDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_eq_band_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_eq_preset_dto(
    List<EqPresetDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_eq_preset_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_playlist_dto(
    List<PlaylistDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_playlist_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_f_32_strict(
    Float32List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat32List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_track_dto(
    List<TrackDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_track_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_wave_group_dto(
    List<WaveGroupDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_wave_group_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_wave_option_dto(
    List<WaveOptionDto> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_wave_option_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_play_source_dto(
    PlaySourceDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.url, serializer);
    sse_encode_String(self.codec, serializer);
    sse_encode_opt_box_autoadd_u_32(self.bitrateKbps, serializer);
    sse_encode_bool(self.isPreview, serializer);
    sse_encode_bool(self.cached, serializer);
  }

  @protected
  void sse_encode_playlist_dto(PlaylistDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_opt_box_autoadd_u_32(self.trackCount, serializer);
    sse_encode_opt_String(self.coverUrl, serializer);
    sse_encode_opt_String(self.ownerUid, serializer);
  }

  @protected
  void sse_encode_s_3_config_dto(S3ConfigDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.endpoint, serializer);
    sse_encode_String(self.region, serializer);
    sse_encode_String(self.bucket, serializer);
    sse_encode_String(self.accessKey, serializer);
    sse_encode_String(self.secretKey, serializer);
    sse_encode_bool(self.pathStyle, serializer);
  }

  @protected
  void sse_encode_s_3_status_dto(S3StatusDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.connected, serializer);
    sse_encode_String(self.endpoint, serializer);
    sse_encode_String(self.region, serializer);
    sse_encode_String(self.bucket, serializer);
    sse_encode_String(self.accessKey, serializer);
    sse_encode_bool(self.pathStyle, serializer);
  }

  @protected
  void sse_encode_s_3_sync_dto(S3SyncDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.uploaded, serializer);
    sse_encode_u_32(self.found, serializer);
    sse_encode_u_32(self.removed, serializer);
  }

  @protected
  void sse_encode_s_3_upload_result_dto(
    S3UploadResultDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.uploaded, serializer);
    sse_encode_list_String(self.failed, serializer);
  }

  @protected
  void sse_encode_search_dto(SearchDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.best, serializer);
    sse_encode_list_artist_dto(self.artists, serializer);
    sse_encode_list_album_dto(self.albums, serializer);
    sse_encode_list_playlist_dto(self.playlists, serializer);
    sse_encode_list_track_dto(self.tracks, serializer);
  }

  @protected
  void sse_encode_track_dto(TrackDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.artists, serializer);
    sse_encode_list_String(self.artistNames, serializer);
    sse_encode_opt_String(self.album, serializer);
    sse_encode_opt_box_autoadd_u_32(self.year, serializer);
    sse_encode_opt_box_autoadd_u_32(self.durationMs, serializer);
    sse_encode_bool(self.available, serializer);
    sse_encode_opt_String(self.coverUrl, serializer);
    sse_encode_String(self.source, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_wave_group_dto(WaveGroupDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_list_wave_option_dto(self.options, serializer);
  }

  @protected
  void sse_encode_wave_option_dto(
    WaveOptionDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.seed, serializer);
    sse_encode_bool(self.isDefault, serializer);
  }

  @protected
  void sse_encode_wave_settings_dto(
    WaveSettingsDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_wave_option_dto(self.activities, serializer);
    sse_encode_list_wave_group_dto(self.groups, serializer);
  }
}
