// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import 'yandex.dart';

// These functions are ignored because they are not marked as `pub`: `confirm_plus`, `meta_from`, `mirror_one`, `remember_meta`, `s3_cached_stream`, `state`, `track_from_meta`, `wipe`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CacheState`

/// Открыть кэш в `dir` и запустить прокси. `default_limit_mb` применяется,
/// если лимит ещё не сохранён.
Future<void> cacheInit({required String dir, required int defaultLimitMb}) =>
    RustLib.instance.api.crateApiCacheCacheInit(
      dir: dir,
      defaultLimitMb: defaultLimitMb,
    );

/// Откуда играть трек: файл из кэша, поток через прокси (с записью в кэш)
/// или напрямую, если автосохранение выключено.
Future<PlaySourceDto> playSource({required TrackDto track}) =>
    RustLib.instance.api.crateApiCachePlaySource(track: track);

/// Скачать трек в кэш вручную. Завершается, когда файл сохранён.
Future<void> cacheDownload({required TrackDto track}) =>
    RustLib.instance.api.crateApiCacheCacheDownload(track: track);

/// id всех треков в кэше (для отметок в списках).
Future<List<String>> cachedIds() =>
    RustLib.instance.api.crateApiCacheCachedIds();

Future<CacheStatsDto> cacheStats() =>
    RustLib.instance.api.crateApiCacheCacheStats();

Future<void> cacheSetLimit({required int limitMb}) =>
    RustLib.instance.api.crateApiCacheCacheSetLimit(limitMb: limitMb);

/// Перенести скачанные треки в другую папку (`None` — папка по умолчанию).
/// Возвращает число перенесённых файлов.
Future<int> cacheSetFolder({String? folder}) =>
    RustLib.instance.api.crateApiCacheCacheSetFolder(folder: folder);

Future<void> cacheSetAuto({required bool enabled}) =>
    RustLib.instance.api.crateApiCacheCacheSetAuto(enabled: enabled);

Future<void> cacheClear() => RustLib.instance.api.crateApiCacheCacheClear();

/// Скопировать в S3 треки локального кэша, которых там ещё нет.
/// Возвращает число скопированных. Без подключённого S3 — 0.
Future<int> cacheMirrorToS3() =>
    RustLib.instance.api.crateApiCacheCacheMirrorToS3();

/// Дописать метаданные и теги трекам, попавшим в кэш без них.
/// Возвращает, скольким трекам дописано. Нужна сеть.
Future<int> cacheBackfillMeta() =>
    RustLib.instance.api.crateApiCacheCacheBackfillMeta();

/// Треки в кэше с метаданными — список «Скачанное», работает без сети.
/// Сначала недавно игравшие.
Future<List<TrackDto>> cachedTracks() =>
    RustLib.instance.api.crateApiCacheCachedTracks();

/// Сохранить обложку папки плейлиста или альбома (`folder.jpg`).
Future<void> cachePlaceFolderCover({
  required String folder,
  required String coverUrl,
}) => RustLib.instance.api.crateApiCacheCachePlaceFolderCover(
  folder: folder,
  coverUrl: coverUrl,
);

/// Положить скачанный трек ещё и в папку плейлиста:
/// `<папка загрузок>/<название плейлиста>/`.
Future<void> cachePlaceInFolder({
  required String trackId,
  required String folder,
}) => RustLib.instance.api.crateApiCacheCachePlaceInFolder(
  trackId: trackId,
  folder: folder,
);

class CacheStatsDto {
  final double usedMb;
  final int limitMb;
  final int tracks;

  /// Сохранять все прослушанные треки.
  final bool autoCache;

  /// Папка с файлами треков.
  final String folder;

  /// Папку выбрал пользователь (а не папка по умолчанию).
  final bool customFolder;

  const CacheStatsDto({
    required this.usedMb,
    required this.limitMb,
    required this.tracks,
    required this.autoCache,
    required this.folder,
    required this.customFolder,
  });

  @override
  int get hashCode =>
      usedMb.hashCode ^
      limitMb.hashCode ^
      tracks.hashCode ^
      autoCache.hashCode ^
      folder.hashCode ^
      customFolder.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CacheStatsDto &&
          runtimeType == other.runtimeType &&
          usedMb == other.usedMb &&
          limitMb == other.limitMb &&
          tracks == other.tracks &&
          autoCache == other.autoCache &&
          folder == other.folder &&
          customFolder == other.customFolder;
}

class PlaySourceDto {
  /// Путь к файлу кэша, адрес локального прокси или прямая ссылка.
  final String url;
  final String codec;
  final int? bitrateKbps;
  final bool isPreview;
  final bool cached;

  const PlaySourceDto({
    required this.url,
    required this.codec,
    this.bitrateKbps,
    required this.isPreview,
    required this.cached,
  });

  @override
  int get hashCode =>
      url.hashCode ^
      codec.hashCode ^
      bitrateKbps.hashCode ^
      isPreview.hashCode ^
      cached.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlaySourceDto &&
          runtimeType == other.runtimeType &&
          url == other.url &&
          codec == other.codec &&
          bitrateKbps == other.bitrateKbps &&
          isPreview == other.isPreview &&
          cached == other.cached;
}
