// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `mode_from`, `mode_to`, `preset_to`, `settings_from`, `settings_to`, `state_to`

EqSettingsDto eqFlat({required EqModeDto mode}) =>
    RustLib.instance.api.crateApiEqEqFlat(mode: mode);

EqSettingsDto eqWithMode({
  required EqSettingsDto settings,
  required EqModeDto mode,
}) => RustLib.instance.api.crateApiEqEqWithMode(settings: settings, mode: mode);

/// Строка для свойства mpv `af`; пустая — обработка выключена.
String eqToFilter({required EqSettingsDto settings}) =>
    RustLib.instance.api.crateApiEqEqToFilter(settings: settings);

/// Предусилитель для громкости плеера (0, если эквалайзер выключен).
double eqEffectivePreamp({required EqSettingsDto settings}) =>
    RustLib.instance.api.crateApiEqEqEffectivePreamp(settings: settings);

double eqAutoPreamp({required EqSettingsDto settings}) =>
    RustLib.instance.api.crateApiEqEqAutoPreamp(settings: settings);

List<EqPresetDto> eqBuiltinPresets({required EqModeDto mode}) =>
    RustLib.instance.api.crateApiEqEqBuiltinPresets(mode: mode);

/// Импорт пресета AutoEq / Equalizer APO (текст файла `ParametricEQ.txt`).
EqSettingsDto eqParseAutoeq({required String text}) =>
    RustLib.instance.api.crateApiEqEqParseAutoeq(text: text);

/// Настройки с учётом S3: берётся более свежая копия (локальная или из
/// бакета), и она же записывается на другую сторону. Без S3 или когда он
/// недоступен (NAS вне дома) — локальные настройки.
Future<EqStateDto> eqSync({required String path}) =>
    RustLib.instance.api.crateApiEqEqSync(path: path);

/// Сохранить локально и (если подключено) в S3. Сбой S3 не мешает
/// локальному сохранению.
Future<void> eqSave({required String path, required EqStateDto state}) =>
    RustLib.instance.api.crateApiEqEqSave(path: path, state: state);

/// Кривая АЧХ (дБ) в `points` точках от 20 Гц до 20 кГц — для дисплея плеера.
Float32List eqResponse({
  required EqSettingsDto settings,
  required int points,
}) => RustLib.instance.api.crateApiEqEqResponse(
  settings: settings,
  points: points,
);

class EqBandDto {
  final FilterKindDto kind;
  final double freqHz;
  final double gainDb;
  final double q;

  const EqBandDto({
    required this.kind,
    required this.freqHz,
    required this.gainDb,
    required this.q,
  });

  @override
  int get hashCode =>
      kind.hashCode ^ freqHz.hashCode ^ gainDb.hashCode ^ q.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EqBandDto &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          freqHz == other.freqHz &&
          gainDb == other.gainDb &&
          q == other.q;
}

enum EqModeDto { graphic10, graphic18, parametric }

class EqPresetDto {
  final String name;
  final EqSettingsDto settings;

  const EqPresetDto({required this.name, required this.settings});

  @override
  int get hashCode => name.hashCode ^ settings.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EqPresetDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          settings == other.settings;
}

class EqSettingsDto {
  final bool enabled;
  final EqModeDto mode;
  final double preampDb;
  final List<EqBandDto> bands;

  const EqSettingsDto({
    required this.enabled,
    required this.mode,
    required this.preampDb,
    required this.bands,
  });

  @override
  int get hashCode =>
      enabled.hashCode ^ mode.hashCode ^ preampDb.hashCode ^ bands.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EqSettingsDto &&
          runtimeType == other.runtimeType &&
          enabled == other.enabled &&
          mode == other.mode &&
          preampDb == other.preampDb &&
          bands == other.bands;
}

class EqStateDto {
  final EqSettingsDto current;
  final List<EqPresetDto> userPresets;

  const EqStateDto({required this.current, required this.userPresets});

  @override
  int get hashCode => current.hashCode ^ userPresets.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EqStateDto &&
          runtimeType == other.runtimeType &&
          current == other.current &&
          userPresets == other.userPresets;
}

enum FilterKindDto { peaking, lowShelf, highShelf }
