// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import 'yandex.dart';

// These functions are ignored because they are not marked as `pub`: `entry_dto`, `http`, `library`, `require`, `resolve`

/// Проверить доступ и сохранить настройки. Возвращает число треков в библиотеке.
Future<int> s3Connect({required S3ConfigDto config}) =>
    RustLib.instance.api.crateApiS3S3Connect(config: config);

Future<S3StatusDto> s3Status() => RustLib.instance.api.crateApiS3S3Status();

/// Забыть настройки и ключи. Данные в бакете не трогаются.
Future<void> s3Disconnect() => RustLib.instance.api.crateApiS3S3Disconnect();

Future<List<TrackDto>> s3Tracks() => RustLib.instance.api.crateApiS3S3Tracks();

/// Загрузить файлы mp3/flac. Ошибки по отдельным файлам не прерывают остальные.
Future<S3UploadResultDto> s3Upload({required List<String> paths}) =>
    RustLib.instance.api.crateApiS3S3Upload(paths: paths);

Future<void> s3Delete({required String trackId}) =>
    RustLib.instance.api.crateApiS3S3Delete(trackId: trackId);

class S3ConfigDto {
  final String endpoint;
  final String region;
  final String bucket;
  final String accessKey;
  final String secretKey;
  final bool pathStyle;

  const S3ConfigDto({
    required this.endpoint,
    required this.region,
    required this.bucket,
    required this.accessKey,
    required this.secretKey,
    required this.pathStyle,
  });

  @override
  int get hashCode =>
      endpoint.hashCode ^
      region.hashCode ^
      bucket.hashCode ^
      accessKey.hashCode ^
      secretKey.hashCode ^
      pathStyle.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is S3ConfigDto &&
          runtimeType == other.runtimeType &&
          endpoint == other.endpoint &&
          region == other.region &&
          bucket == other.bucket &&
          accessKey == other.accessKey &&
          secretKey == other.secretKey &&
          pathStyle == other.pathStyle;
}

/// Текущие настройки без секретного ключа.
class S3StatusDto {
  final bool connected;
  final String endpoint;
  final String region;
  final String bucket;
  final String accessKey;
  final bool pathStyle;

  const S3StatusDto({
    required this.connected,
    required this.endpoint,
    required this.region,
    required this.bucket,
    required this.accessKey,
    required this.pathStyle,
  });

  @override
  int get hashCode =>
      connected.hashCode ^
      endpoint.hashCode ^
      region.hashCode ^
      bucket.hashCode ^
      accessKey.hashCode ^
      pathStyle.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is S3StatusDto &&
          runtimeType == other.runtimeType &&
          connected == other.connected &&
          endpoint == other.endpoint &&
          region == other.region &&
          bucket == other.bucket &&
          accessKey == other.accessKey &&
          pathStyle == other.pathStyle;
}

class S3UploadResultDto {
  final int uploaded;

  /// «файл: причина» для не загрузившихся.
  final List<String> failed;

  const S3UploadResultDto({required this.uploaded, required this.failed});

  @override
  int get hashCode => uploaded.hashCode ^ failed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is S3UploadResultDto &&
          runtimeType == other.runtimeType &&
          uploaded == other.uploaded &&
          failed == other.failed;
}
