// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import 'yandex.dart';

// These functions are ignored because they are not marked as `pub`: `reset`

/// Запустить волну. `learning = false` — тихий режим: incognito, отчёты не отправляются.
Future<List<TrackDto>> waveStart({required bool learning}) =>
    RustLib.instance.api.crateApiWaveWaveStart(learning: learning);

/// Следующая партия треков текущей волны.
Future<List<TrackDto>> waveMore() =>
    RustLib.instance.api.crateApiWaveWaveMore();

Future<void> waveTrackStarted({required String trackId}) =>
    RustLib.instance.api.crateApiWaveWaveTrackStarted(trackId: trackId);

/// `skipped = false` — трек дослушан до конца.
Future<void> waveTrackEnded({
  required String trackId,
  required double playedSecs,
  required bool skipped,
}) => RustLib.instance.api.crateApiWaveWaveTrackEnded(
  trackId: trackId,
  playedSecs: playedSecs,
  skipped: skipped,
);

Future<void> waveStop() => RustLib.instance.api.crateApiWaveWaveStop();
