// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `account_dto`, `album_dto`, `artist_dto`, `playlist_dto`, `provider`, `reset_provider`, `run`, `secrets`, `stream_dto`, `track_dto`, `track_dtos`

/// Вызывается первым при запуске. `data_dir` — приватная папка приложения:
/// на Android секреты лежат в ней, на десктопе — в системном хранилище.
Future<void> appInit({required String dataDir}) =>
    RustLib.instance.api.crateApiYandexAppInit(dataDir: dataDir);

Future<bool> isLoggedIn() => RustLib.instance.api.crateApiYandexIsLoggedIn();

/// Шаг 1 входа: получить код, который пользователь вводит на сайте Яндекса.
Future<DeviceCodeDto> startLogin() =>
    RustLib.instance.api.crateApiYandexStartLogin();

/// Шаг 2 входа: дождаться подтверждения и сохранить токен.
Future<AccountDto> finishLogin() =>
    RustLib.instance.api.crateApiYandexFinishLogin();

Future<void> logout() => RustLib.instance.api.crateApiYandexLogout();

Future<AccountDto> account() => RustLib.instance.api.crateApiYandexAccount();

Future<List<TrackDto>> likedTracks() =>
    RustLib.instance.api.crateApiYandexLikedTracks();

Future<List<PlaylistDto>> playlists() =>
    RustLib.instance.api.crateApiYandexPlaylists();

/// Треки плейлиста; `owner_uid` — для чужих плейлистов (из поиска).
Future<List<TrackDto>> playlistTracks({required String id, String? ownerUid}) =>
    RustLib.instance.api.crateApiYandexPlaylistTracks(
      id: id,
      ownerUid: ownerUid,
    );

/// Общий поиск по разделам.
Future<SearchDto> searchAll({required String query}) =>
    RustLib.instance.api.crateApiYandexSearchAll(query: query);

/// Страница исполнителя.
Future<ArtistPageDto> artistPage({required String id}) =>
    RustLib.instance.api.crateApiYandexArtistPage(id: id);

/// Все треки исполнителя.
Future<List<TrackDto>> artistTracks({required String id}) =>
    RustLib.instance.api.crateApiYandexArtistTracks(id: id);

/// Лайкнутые альбомы.
Future<List<AlbumDto>> likedAlbums() =>
    RustLib.instance.api.crateApiYandexLikedAlbums();

/// Треки альбома (все диски подряд).
Future<List<TrackDto>> albumTracks({required String id}) =>
    RustLib.instance.api.crateApiYandexAlbumTracks(id: id);

Future<List<TrackDto>> search({required String query}) =>
    RustLib.instance.api.crateApiYandexSearch(query: query);

Future<StreamDto> streamUrl({
  required String trackId,
  required bool lowQuality,
}) => RustLib.instance.api.crateApiYandexStreamUrl(
  trackId: trackId,
  lowQuality: lowQuality,
);

class AccountDto {
  final String uid;
  final String name;
  final bool hasPlus;

  const AccountDto({
    required this.uid,
    required this.name,
    required this.hasPlus,
  });

  @override
  int get hashCode => uid.hashCode ^ name.hashCode ^ hasPlus.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AccountDto &&
          runtimeType == other.runtimeType &&
          uid == other.uid &&
          name == other.name &&
          hasPlus == other.hasPlus;
}

class AlbumDto {
  final String id;
  final String title;
  final String artists;
  final int? year;
  final String? coverUrl;
  final int? trackCount;

  /// Имя папки для скачанного альбома: «Исполнитель — Альбом (год)».
  final String folderName;

  const AlbumDto({
    required this.id,
    required this.title,
    required this.artists,
    this.year,
    this.coverUrl,
    this.trackCount,
    required this.folderName,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      artists.hashCode ^
      year.hashCode ^
      coverUrl.hashCode ^
      trackCount.hashCode ^
      folderName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AlbumDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          artists == other.artists &&
          year == other.year &&
          coverUrl == other.coverUrl &&
          trackCount == other.trackCount &&
          folderName == other.folderName;
}

class ArtistDto {
  final String id;
  final String name;
  final String? coverUrl;

  const ArtistDto({required this.id, required this.name, this.coverUrl});

  @override
  int get hashCode => id.hashCode ^ name.hashCode ^ coverUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ArtistDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          coverUrl == other.coverUrl;
}

class ArtistPageDto {
  final ArtistDto artist;
  final List<TrackDto> popularTracks;
  final List<AlbumDto> albums;

  /// Сборники и альбомы с участием.
  final List<AlbumDto> alsoAlbums;

  const ArtistPageDto({
    required this.artist,
    required this.popularTracks,
    required this.albums,
    required this.alsoAlbums,
  });

  @override
  int get hashCode =>
      artist.hashCode ^
      popularTracks.hashCode ^
      albums.hashCode ^
      alsoAlbums.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ArtistPageDto &&
          runtimeType == other.runtimeType &&
          artist == other.artist &&
          popularTracks == other.popularTracks &&
          albums == other.albums &&
          alsoAlbums == other.alsoAlbums;
}

class DeviceCodeDto {
  final String userCode;
  final String verificationUrl;

  /// Сколько секунд действует код.
  final int expiresIn;

  const DeviceCodeDto({
    required this.userCode,
    required this.verificationUrl,
    required this.expiresIn,
  });

  @override
  int get hashCode =>
      userCode.hashCode ^ verificationUrl.hashCode ^ expiresIn.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeviceCodeDto &&
          runtimeType == other.runtimeType &&
          userCode == other.userCode &&
          verificationUrl == other.verificationUrl &&
          expiresIn == other.expiresIn;
}

class PlaylistDto {
  final String id;
  final String title;
  final int? trackCount;
  final String? coverUrl;

  /// Владелец — для чужих плейлистов из поиска; для своих можно не указывать.
  final String? ownerUid;

  const PlaylistDto({
    required this.id,
    required this.title,
    this.trackCount,
    this.coverUrl,
    this.ownerUid,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      trackCount.hashCode ^
      coverUrl.hashCode ^
      ownerUid.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlaylistDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          trackCount == other.trackCount &&
          coverUrl == other.coverUrl &&
          ownerUid == other.ownerUid;
}

class SearchDto {
  /// Тип лучшего совпадения: `artist`, `album`, `track`, `playlist`.
  final String? best;
  final List<ArtistDto> artists;
  final List<AlbumDto> albums;
  final List<PlaylistDto> playlists;
  final List<TrackDto> tracks;

  const SearchDto({
    this.best,
    required this.artists,
    required this.albums,
    required this.playlists,
    required this.tracks,
  });

  @override
  int get hashCode =>
      best.hashCode ^
      artists.hashCode ^
      albums.hashCode ^
      playlists.hashCode ^
      tracks.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchDto &&
          runtimeType == other.runtimeType &&
          best == other.best &&
          artists == other.artists &&
          albums == other.albums &&
          playlists == other.playlists &&
          tracks == other.tracks;
}

class StreamDto {
  final String url;
  final String codec;
  final int? bitrateKbps;
  final bool isPreview;

  const StreamDto({
    required this.url,
    required this.codec,
    this.bitrateKbps,
    required this.isPreview,
  });

  @override
  int get hashCode =>
      url.hashCode ^ codec.hashCode ^ bitrateKbps.hashCode ^ isPreview.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StreamDto &&
          runtimeType == other.runtimeType &&
          url == other.url &&
          codec == other.codec &&
          bitrateKbps == other.bitrateKbps &&
          isPreview == other.isPreview;
}

class TrackDto {
  final String id;

  /// Название вместе с версией.
  final String title;

  /// Исполнители одной строкой для показа.
  final String artists;

  /// Исполнители по отдельности (для тегов файла).
  final List<String> artistNames;
  final String? album;
  final int? year;
  final int? durationMs;
  final bool available;
  final String? coverUrl;

  /// Откуда трек: `yandex` или `s3` (собственная библиотека).
  final String source;

  const TrackDto({
    required this.id,
    required this.title,
    required this.artists,
    required this.artistNames,
    this.album,
    this.year,
    this.durationMs,
    required this.available,
    this.coverUrl,
    required this.source,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      artists.hashCode ^
      artistNames.hashCode ^
      album.hashCode ^
      year.hashCode ^
      durationMs.hashCode ^
      available.hashCode ^
      coverUrl.hashCode ^
      source.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TrackDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          artists == other.artists &&
          artistNames == other.artistNames &&
          album == other.album &&
          year == other.year &&
          durationMs == other.durationMs &&
          available == other.available &&
          coverUrl == other.coverUrl &&
          source == other.source;
}
